apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mobilenet-v3-small
  namespace: kserve-test
  annotations:
    serving.kserve.io/enable-metric-aggregation: "true"
    serving.kserve.io/enable-prometheus-scraping: "true"
spec:
  predictor:
    timeout: 120
    minReplicas: 1
    maxReplicas: 1
    containerConcurrency: 0
    model:
      protocolVersion: v2
      modelFormat:
        name: onnx
      runtime: kserve-tritonserver
      storageUri: "pvc://resnet-pvc/onnx-repository/"
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
