apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mobilenet-v3-large
  namespace: kserve-test
  annotations:
    serving.kserve.io/enable-metric-aggregation: "true"
    serving.kserve.io/enable-prometheus-scraping: "true"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    containerConcurrency: 0
    model:
      modelFormat:
        name: tensorflow
      runtime: kserve-tensorflow-serving
      storageUri: "pvc://resnet-pvc/mobilenet-v3-large/"
      resources:
        requests:
          cpu: "1"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
