apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: resnet50
  namespace: kserve-test
  annotations:
    serving.kserve.io/enable-metric-aggregation: "true"
    serving.kserve.io/enable-prometheus-scraping: "true"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    containerConcurrency: 0 # 무제한
    model:
      protocolVersion: v2
      modelFormat:
        name: onnx
      runtime: kserve-tritonserver
      storageUri: "pvc://resnet-pvc/onnx-repository/"
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "2"
          memory: "8Gi"
